###
GET http://localhost:4000/api/pc

###
PUT http://localhost:4000/api/pc
content-type: application/json

{
    "state": "on"
}

###
PUT http://localhost:4000/api/lifx
content-type: application/json

{
    "state": "off"
}
